kind = "web"
previewPath = "/"
title = "Разработка буклета АГ — Москомархитектура"
version = "1.0.0"
id = "artifacts/ag-booklet"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
localPort = 20639
name = "web"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/ag-booklet run dev"

[services.env]
PORT = "20639"
BASE_PATH = "/"

[services.production]
build = ["pnpm", "--filter", "@workspace/ag-booklet", "run", "build"]

[services.production.run]
args = ["pnpm", "--filter", "@workspace/ag-booklet", "run", "serve"]

[services.production.run.env]
PORT = "20639"
BASE_PATH = "/"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"
